# Generic multicopter configuration

[info]
key = "6xpi"
description = "mc"
mass = 1.8
[rotor_default]
axis      = [0.0, 0.0, -1.0]
Ct        = 7.426e-06
Cm        = 2.0e-07

[[rotors]]
name      = "rotor_1"
position  = [0.0, 0.25, 0.0]
direction = "CW"

[[rotors]]
name      = "rotor_2"
position  = [0.0, -0.25, 0.0]
direction = "CCW"

[[rotors]]
name      = "rotor_3"
position  = [0.2165, -0.125, 0.0]
direction = "CW"

[[rotors]]
name      = "rotor_4"
position  = [-0.2165, 0.125, 0.0]
direction = "CCW"

[[rotors]]
name      = "rotor_5"
position  = [0.2165, 0.125, 0.0]
direction = "CCW"

[[rotors]]
name      = "rotor_6"
position  = [-0.2165, -0.125, 0.0]
direction = "CW"

