# Generic multicopter configuration

[info]
key = "6xp"
description = "mc"

[rotor_default]
axis      = [0.0, 0.0, -1.0]
Ct        = 8.54858e-06
Cm        = 0.05

[[rotors]]
name      = "rotor_0"
position  = [0.2165, 0.125, 0.0]
direction = "CW"

[[rotors]]
name      = "rotor_1"
position  = [-0.125, 0.2165, 0.0]
direction = "CCW"

[[rotors]]
name      = "rotor_2"
position  = [-0.2165, -0.125, 0.0]
direction = "CW"

[[rotors]]
name      = "rotor_3"
position  = [0.125, -0.2165, 0.0]
direction = "CCW"

